### ISSUE TITLE
'aliases' is not saved

### ISSUE THREAD

**Issue by klemenag** [rplessl/roundcube-vacation-plugin#18]
roundcube 1.3.9
php 5.6.40
latest vacation plugin with setuid driver

Scenario :

- enable OutOfOffice (OOO) (tick the 'Send a notification' checkbox)
- save
- add some alias addresses
- save
- disable OutOfOffice (OOO) (untick the 'Send a notification' checkbox)
- save

Should be scenario : OOO is disabled, aliases list remains in the checkbox
What actually happens : OOO is disabled, aliases list is cleared (empty) and cannot be retrieved

Is this a bug or a feature?

**Comment by mnheia** [comment]
It looks like this is designed. It removes everything after and including |/usr/bin/vacation ... including -a which are the aliases. If we would keep the -a in file perhaps seperated by | and read this should work.

**Comment by rplessl** [comment]
feel free to enhance :-)

**Comment by rplessl** [comment]
I will not fix it (this project fork will be archived)
