### ISSUE TITLE
File does not exist: $skin_path

### ISSUE THREAD

**Issue by thom1214** [rplessl/roundcube-vacation-plugin#22]
My apache's error log moans about:
File does not exist: /srv/www/roundcubemail-1.3.9/$skin_path, referer: http://my.server.tld/roundcubemail139/?_task=settings&_action=plugin.vacation

The plugin itself and roundcubemail works fine but I like to get rid of the error. I think it's an configuration issue. How do I have to set $skin_path ?

Thanks

Thom

**Comment by rplessl** [comment]
should be part of the general roundcubemail configuration

**Comment by rplessl** [comment]
I will not fix it (this project fork will be archived)
