### ISSUE TITLE
vacation plugin not working php7

### ISSUE THREAD

**Issue by rudyvdb** [rplessl/roundcube-vacation-plugin#4]
Hello
I tried this plugin before without any issue. Have new server now with Debian 9 (php7 installed), but now the vacation plugin is not working)
Any help?
Thanks

**Comment by rplessl** [comment]
could you try the new plugin version ready for roundcube 1.3?

**Comment by rplessl** [comment]
@rudyvdb is this issue for you still open?

**Comment by shinobi31337** [comment]
Have installed roundcube 1.4 from git and the latest vacation plugin with php 7.2. it doesnt have active from/activeuntil checkbox in UI. Also, there are some differences in database structure, like cache column that is absent in old version of plugin.

**Comment by oleh83** [comment]
Hello, In the last version Ubuntu 18.04 with Php7 - not working.

**Comment by rplessl** [comment]
I will not fix it (this project fork will be archived)
